# Generated by Django 4.0.4 on 2022-07-17 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_image_product_image_2_product_image_3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_5',
        ),
    ]
